#- alias: Living Room Motion
#  trigger: 
#    platform: state
#    entity_id: binary_sensor.pir_living_room
#    to: 'on'
#  action:
#    - service: script.turn_on
#      entity_id: script.living_room_motion

- alias: Day - Living Room Motion
  trigger:
    - platform: state
      entity_id: binary_sensor.pir_living_room
      to: 'on'
  condition:
#    - condition: state
#      entity_id: sun.sun
#      state: 'above_horizon'
    - condition: state
      entity_id: switch.living_room_lights
      state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.living_room_lights

- alias: Lights on when motion
  trigger:
    - platform: state
      entity_id: binary_sensor.pir_living_room
      to: 'on'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: group.kitchen_lights
      state: 'off'
  action:
    - service: light.turn_on
      entity_id: group.kitchen_lights
      data:
        brightness: 28

- alias: Light off after 10 min of no motion
  trigger:
    - platform: state
      entity_id: binary_sensor.pir_living_room
      to: 'off'
      for:
        minutes: 10
  condition:
    - condition: time
      after: '23:15:00'
      before: '08:00:00'
  action:
    - service_template: light.turn_off
      entity_id: group.kitchen_lights
