- alias: Day - Living Room Motion
  trigger:
    - platform: state
      entity_id: binary_sensor.living_room_motion
      to: 'on'
  condition:
    - condition: state
      entity_id: binary_sensor.sun_down
      state: 'off'
    - condition: state
      entity_id: group.living_room_lights
      state: 'off'
  action:
    - service: light.turn_on
      entity_id: group.living_room_lights
      data:
        brightness_pct: 80

- alias: Day - Lights off after 30 min of no motion
  trigger:
    - platform: state
      entity_id: binary_sensor.living_room_motion
      to: 'off'
      for:
        minutes: 30
  condition:
    - condition: state
      entity_id: binary_sensor.sun_down
      state: 'off'
  action:
    - service: light.turn_off
      entity_id: group.living_room_lights

- alias: Night - Lights on when motion
  trigger:
    - platform: state
      entity_id: group.house_motion
      to: 'on'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: group.kitchen_lights
      state: 'off'
  action:
    - service: light.turn_on
      entity_id:
        - light.oven
        - light.sink
        - light.behind_tv_lamp
      data:
        brightness: 28
        transition: 3
    - service: light.turn_on
      entity_id: light.kitchen_cabinet
      data:
        brightness: 15
        white_value: 5
        rgb_color: [255, 61, 0]
    - service: light.turn_on
      entity_id: group.mood_lights
      data:
        rgb_color: [63,12,0]
        brightness_pct: 25
        transition: 3

- alias: Night - Light off after 20 min of no motion
  trigger:
    - platform: time_pattern
      minutes: '/5'
      seconds: 00
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.house_motion
        state: 'off'
        for:
          minutes: 20
      - condition: time
        after: '22:30:00'
        before: '08:00:00'
  action:
    - service: scene.turn_on
      entity_id: scene.bed_time

