- alias: Day - Living Room Motion
  trigger:
    - platform: state
      entity_id: binary_sensor.pir_living_room
      to: 'on'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'above_horizon'
    - condition: state
      entity_id: switch.living_room_lights
      state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.living_room_lights

- alias: Day - Lights off after 30 min of no motion
  trigger:
    - platform: state
      entity_id: binary_sensor.pir_living_room
      to: 'off'
      for:
        minutes: 30
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'above_horizon'
  action:
    - service_template: switch.turn_off
      entity_id: switch.living_room_lights

- alias: Lights on when motion
  trigger:
    - platform: state
      entity_id: binary_sensor.pir_living_room
      to: 'on'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: group.kitchen_lights
      state: 'off'
  action:
    - service: light.turn_on
      entity_id: group.kitchen_lights
      data:
        brightness: 28
    - service: light.turn_on
      entity_id: group.mood_lights
      data:
        rgb_color: [63,12,0]
        brightness_pct: 25

- alias: Night- Light off after 20 min of no motion
  trigger:
    - platform: state
      entity_id: binary_sensor.pir_living_room
      to: 'off'
      for:
        minutes: 20
  condition:
    - condition: time
      after: '23:15:00'
      before: '08:00:00'
  action:
    - service_template: light.turn_off
      entity_id: group.kitchen_lights
    - service_template: light.turn_off
      entity_id: group.mood_lights

- alias: Fam Away Motion Alert
  trigger:
    - platform: state
      entity_id: binary_sensor.pir_living_room
      to: 'on'
  condition:
    - condition: state
    entity_id: group.family
    state: 'not home'
  action:
    - service: notify.facebook
      data:
        message: 'Motion at home'
        target:
          - !secret spencer_number
