language: python
python: "3.8"

sudo: required

before_install:
  - touch home-assistant_v2.db
  - touch home-assistant.log
  - sudo mkdir -p /ssl
  - sudo touch /ssl/fullchain.pem
  - sudo touch /ssl/privkey.pem
  - mv github_resources/secrets_redacted.yaml secrets.yaml
  - mv github_resources/google_account_redacted.json google_account.json
  - sudo apt-get install libudev-dev libswscale-dev libavfilter-dev libavdevice-dev

install: pip3 install homeassistant

script: hass -c . --script check_config -f
