homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 22
  unit_system: imperial
  time_zone: America/New_York
  customize: !include_dir_merge_named customize
  auth_providers:
   - type: homeassistant

auth:

zone: !include ./configuration/zone.yaml

frontend:
  extra_html_url:
    - /local/custom_ui/state-card-tiles.html
  extra_html_url_es5:
    - /local/custom_ui/state-card-tiles_es5.html
  themes: !include_dir_merge_named themes/

lovelace:
  mode: yaml

config:

http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  base_url: !secret base_url

# Checks for available updates
updater:
  include_used_components: true
# Discover some devices automatically
discovery:
# Enables support for tracking state changes over time.
history:
# View all events in a logbook
# logbook:
recorder:
  purge_keep_days: 3

sun:

automation: !include_dir_merge_list automation
group: !include ./configuration/group.yaml
notify: !include ./configuration/notify.yaml
scene: !include_dir_merge_list scene
sensor: !include ./configuration/sensor.yaml
binary_sensor: !include ./configuration/binary_sensor.yaml
script: !include_dir_merge_named script
light: !include ./configuration/light.yaml
switch: !include ./configuration/switch.yaml

# Allows you to issue voice commands from the frontend in enabled browsers
# conversation:
# Text to speech
tts:
  platform: google

zwave:
  usb_path: /dev/ttyACM0

device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.0.100-140
    scan_options: " -sn "
  - platform: google_maps
    username: !secret google_location_account
    password: !secret google_location_password
  - platform: bluetooth_tracker

map:

hdmi_cec:
  devices:
    TV: 0.0.0.0

google_assistant:
  project_id: soberstadt
  api_key: !secret google_api_api_key
  entity_config:
    light.ge_12724_3way_dimmer_switch_level:
      name: Bedroom Lights
      expose: true
      room: Bedroom
    light.flux_bedroom:
      name: Bedroom Mood
      expose: true
      room: Mood
    light.6001948a98a2_1921680101:
      name: Living Mood Light
      expose: true
      room: Mood
    switch.sonoff_1:
      name: Sitting Room Lamp
      expose: true
      room: Sitting Room
    climate.2gig_technologies_ct101_thermostat_iris_cooling_1:
      name: Thermostat
      expose: true
      room: Entryway
  expose_by_default: false

tuya:
  username: !secret tuya_username
  password: !secret tuya_password
  country_code: 1

input_text:
  roku_remote_ip:
    name: Roku Remote IP
input_boolean:
  scene_tiles:
  house_state_tiles:
input_select:
  spencer_status_dropdown:
    name: Spencer
    options:
      - Home
      - Just Arrived
      - Just Left
      - Away
      - Extended Away
      - Work
  lynsey_status_dropdown:
    name: Lynsey
    options:
      - Home
      - Just Arrived
      - Just Left
      - Away
      - Extended Away
      - Work
  family_status_dropdown:
    name: Family Presence
    options:
      - Home
      - Just Arrived
      - Just Left
      - Away
      - Extended Away
      - Work
  hass_theme:
    name: Themes
    options:
      - default
      - midnight
    initial: default

# custom components:
roku_remote:
custom_updater:

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: homeassistant
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state

panel_iframe:
  influx:
    title: InfluxDB
    icon: mdi:chart-areaspline
    url: http://192.168.0.190:8888
  grafana:
    title: Grafana
    icon: mdi:chart-timeline
    url: http://192.168.0.190:3001

meross:
  username: !secret meross_username
  password: !secret meross_password

python_script:
