homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 22
  unit_system: imperial
  time_zone: America/New_York
  customize: !include_dir_merge_named customize
  auth_providers:
    - type: homeassistant
  external_url: !secret ha_url
  internal_url: !secret internal_url

auth:

zone: !include ./configuration/zone.yaml

frontend:
  themes: !include_dir_merge_named themes/

lovelace:
  mode: yaml
  resources:
    # local copy of card that I have edited
    - url: /local/thermostat-card.js?v=1.1
      type: module
    # cards loaded via hacs
    - url: /hacsfiles/custom-header/custom-header.js
      type: module
    - url: /hacsfiles/mini-media-player/mini-media-player.js
      type: module
    - url: /hacsfiles/roku-card/roku-card.js
      type: module
    - url: /hacsfiles/simple-weather-card/simple-weather-card-bundle.js
      type: module
    - url: /hacsfiles/light-entity-card/light-entity-card.js
      type: js

config:

http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

# Checks for available updates
updater:
  include_used_components: true
# Discover some devices automatically
discovery:
# Enables support for tracking state changes over time.
history:
# View all events in a logbook
logbook:
recorder:
  purge_keep_days: 3
  commit_interval: 5
  exclude:
    domains:
      - automation
      - updater
    entity_globs:
      - media_player.*
    entities:
      - sun.sun

sun:
system_health:

automation: !include_dir_merge_list automation
group: !include ./configuration/group.yaml
notify: !include ./configuration/notify.yaml
scene: !include_dir_merge_list scene
sensor: !include ./configuration/sensor.yaml
binary_sensor: !include ./configuration/binary_sensor.yaml
script: !include_dir_merge_named script
light: !include ./configuration/light.yaml
switch: !include ./configuration/switch.yaml
cover: !include ./configuration/cover.yaml

# Allows you to issue voice commands from the frontend in enabled browsers
# conversation:
# Text to speech
tts:
  platform: google_translate

zwave:
  usb_path: /dev/ttyACM0
  device_config:
    light.ge_12724_3way_dimmer_switch_level:
      polling_intensity: 1

device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.0.100-140
    scan_options: " -sn "

mobile_app:

map:

panel_iframe:
  chowdown:
    title: "Recipes"
    icon: mdi:chef-hat
    url: "https://soberstadt.github.io/chowdown/"

speedtestdotnet:
  monitored_conditions:
    - ping
    - download

weather:
  - platform: darksky
    api_key: !secret darksky
    mode: daily

google_assistant:
  project_id: soberstadt
  service_account: !include google_account.json
  secure_devices_pin: !secret google_pin
  report_state: true
  entity_config:
    light.ge_12724_3way_dimmer_switch_level:
      name: Bedroom Lights
      expose: true
      room: Bedroom
    light.flux_bedroom:
      name: Bedroom Mood
      expose: true
      room: Mood
    light.6001948a98a2_1921680101:
      name: Living Mood Light
      expose: true
      room: Mood
    light.flux_lily_bedroom:
      name: Lily Night Light
      expose: true
      room: Lily's room
    light.kitchen_cabinet:
      name: Kitchen Cabinet Light
      expose: true
      room: Kitchen
    switch.sonoff_1:
      name: Sitting Room Lamp
      expose: true
      room: Sitting Room
    climate.2gig_technologies_ct101_thermostat_iris_mode:
      name: Thermostat
      expose: true
      room: Entryway
    cover.garage_door:
      name: Garage Door
      expose: true
      room: Garage
    scene.darkroom:
      name: Darkroom Scene
      expose: true
      room: Bedroom
    scene.romantic:
      name: Romantic Scene
      expose: true
      room: Bedroom
    scene.evening:
      name: Evening Scene
      expose: true
    scene.movie_playing:
      name: Movie Scene
      expose: true
    scene.lily_bed_time:
      name: Lily's Bed Time
      expose: true
      room: Lily's Room
    script.good_night:
      name: Good Night Script
      expose: true
    script.five_more_minutes:
      name: Five More Minutes
      expose: true
      room: Bedroom
    input_boolean.guest_mode:
      name: Guest Mode
      expose: true
    script.roku_play_pause:
      name: Roku Play Pause
      expose: true
  expose_by_default: false

vesync:
  username: !secret vesync_username
  password: !secret vesync_password

stream:

camera:
  - platform: ffmpeg
    input: !secret front_door_camera_url
    name: Front Door

input_boolean:
  guest_mode:
input_select:
  spencer_status_dropdown:
    name: Spencer
    options:
      - Home
      - Just Arrived
      - Just Left
      - Away
      - Extended Away
      - Work
  lynsey_status_dropdown:
    name: Lynsey
    options:
      - Home
      - Just Arrived
      - Just Left
      - Away
      - Extended Away
      - Work
  family_status_dropdown:
    name: Family Presence
    options:
      - Home
      - Just Arrived
      - Just Left
      - Away
      - Extended Away
      - Work
  lily_door_status_dropdown:
    name: Lily's Door Status
    options:
      - Closed
      - Open
      - Unavailable
  hass_theme:
    name: Themes
    options:
      - default
      - midnight
      - clear
      - clear-dark
input_number:
  home_temperature:
    name: Home Temperature
    min: 71
    max: 75
    step: 1
input_datetime:
  weekday_wakeup:
    name: Weekday Wakeup Time
    has_date: false
    has_time: true
  weekend_wakeup:
    name: Weekend Wakeup Time
    has_date: false
    has_time: true
  special_wakeup:
    name: Special Wakeup Time
    has_date: false
    has_time: true
  bedtime:
    name: Bedtime
    has_date: false
    has_time: true

# custom components:
hacs:
  token: !secret hacs_token

# influxdb:
#   host: a0d7b954-influxdb
#   port: 8086
#   database: homeassistant
#   username: homeassistant
#   password: !secret influxdb_password
#   max_retries: 3
#   default_measurement: state

python_script:
