homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 22
  unit_system: imperial
  time_zone: America/New_York
  customize: !include_dir_merge_named customize
  auth_providers:
    - type: homeassistant

auth:

zone: !include ./configuration/zone.yaml

frontend:
  themes: !include_dir_merge_named themes/

lovelace:
  mode: yaml

config:

http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  base_url: !secret base_url

# Checks for available updates
updater:
  include_used_components: true
# Discover some devices automatically
discovery:
# Enables support for tracking state changes over time.
history:
# View all events in a logbook
# logbook:
recorder:
  purge_keep_days: 3

sun:
system_health:

automation: !include_dir_merge_list automation
group: !include ./configuration/group.yaml
notify: !include ./configuration/notify.yaml
scene: !include_dir_merge_list scene
sensor: !include ./configuration/sensor.yaml
binary_sensor: !include ./configuration/binary_sensor.yaml
script: !include_dir_merge_named script
light: !include ./configuration/light.yaml
switch: !include ./configuration/switch.yaml
cover: !include ./configuration/cover.yaml

# Allows you to issue voice commands from the frontend in enabled browsers
# conversation:
# Text to speech
tts:
  platform: google_translate

zwave:
  usb_path: /dev/ttyACM0
  device_config:
    light.ge_12724_3way_dimmer_switch_level:
      polling_intensity: 1

device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.0.100-140
    scan_options: " -sn "
  - platform: google_maps
    username: !secret google_location_account

mobile_app:

map:

speedtestdotnet:
  monitored_conditions:
    - ping
    - download

google_assistant:
  project_id: soberstadt
  service_account: !include google_account.json
  secure_devices_pin: !secret google_pin
  report_state: true
  entity_config:
    light.ge_12724_3way_dimmer_switch_level:
      name: Bedroom Lights
      expose: true
      room: Bedroom
    light.flux_bedroom:
      name: Bedroom Mood
      expose: true
      room: Mood
    light.6001948a98a2_1921680101:
      name: Living Mood Light
      expose: true
      room: Mood
    light.flux_lily_bedroom:
      name: Lily Night Light
      expose: true
      room: Lily's room
    switch.sonoff_1:
      name: Sitting Room Lamp
      expose: true
      room: Sitting Room
    climate.2gig_technologies_ct101_thermostat_iris_mode:
      name: Thermostat
      expose: true
      room: Entryway
    cover.garage_door:
      name: Garage Door
      expose: true
      room: Garage
  expose_by_default: false

tuya:
  username: !secret tuya_username
  password: !secret tuya_password
  country_code: 1

stream:

camera:
  - platform: ffmpeg
    input: !secret front_door_camera_url
    name: Front Door

input_boolean:
  guest_mode:
input_select:
  spencer_status_dropdown:
    name: Spencer
    options:
      - Home
      - Just Arrived
      - Just Left
      - Away
      - Extended Away
      - Work
  lynsey_status_dropdown:
    name: Lynsey
    options:
      - Home
      - Just Arrived
      - Just Left
      - Away
      - Extended Away
      - Work
  family_status_dropdown:
    name: Family Presence
    options:
      - Home
      - Just Arrived
      - Just Left
      - Away
      - Extended Away
      - Work
  hass_theme:
    name: Themes
    options:
      - default
      - midnight
      - clear
      - clear-dark

# custom components:
hacs:
  token: !secret hacs_token

# influxdb:
#   host: a0d7b954-influxdb
#   port: 8086
#   database: homeassistant
#   username: homeassistant
#   password: !secret influxdb_password
#   max_retries: 3
#   default_measurement: state

meross_cloud:
  username: !secret meross_username
  password: !secret meross_password

python_script:
