title: Oberstadt Home
resources:
  - url: /local/button-card.js?v=0.0.5.1
    type: module
  - url: /local/mini-media-player.js?v=0.1
    type: js
  - url: /local/thermostat-card.js?v=1.1
    type: module
excluded_entities:
views:
  - id: 0  # Automatically created id
    icon: mdi:home
    cards:
      - id: c9f11fedade648f5a56af91007986c32  # Automatically created id
        type: glance
        columns: 6
        entities:
          - entity: sensor.arrow_2_real_feel
            name: Inside
          - entity: sensor.dark_sky_apparent_temperature
            name: Outside
          - entity: group.house_motion
            icon: mdi:run-fast
            name: Motion
          - entity: input_select.spencer_status_dropdown
            icon: mdi:account
          - entity: input_select.lynsey_status_dropdown
            icon: mdi:account
          - entity: binary_sensor.garage_door
            name: Garage Door
      - id: b5080a0c1187408cae93b18ccc1223c9  # Automatically created id
        type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: entity-button
                entity: scene.evening
                icon: mdi:weather-sunset
                name: Evening
                service: scene.turn_on
                tap_action: call-service
              - type: entity-button
                entity: scene.bed_time
                icon: mdi:weather-night
                name: Bed Time
                service: scene.turn_on
                tap_action: call-service
              - type: entity-button
                entity: scene.good_night
                icon: mdi:sleep
                name: All Off
                service: scene.turn_on
                tap_action: call-service
          - type: horizontal-stack
            cards:
              - type: entity-button
                entity: scene.romantic
                icon: mdi:heart
                name: Romantic
                service: scene.turn_on
                tap_action: call-service
              - type: entity-button
                entity: script.wii
                icon: mdi:gamepad-variant
                name: Wii
                service: script.turn_on
                tap_action: call-service
              - type: entity-button
                entity: scene.movie_playing
                icon: mdi:movie
                name: Movie
                service: scene.turn_on
                tap_action: call-service
      - id: 148c092bb96847df98155f335be42be2  # Automatically created id
        type: entities
        title: Light Groups
        entities:
          - light.living_room_lights
          - light.kitchen_lights
          - light.bedroom_lights
          - light.sitting_room_lights
          - light.mood_lights
      - type: conditional
        conditions:
          - entity: climate.2gig_technologies_ct101_thermostat_iris_cooling_1
            state_not: "heat"
        card:
          type: custom:thermostat-card
          entity:  climate.2gig_technologies_ct101_thermostat_iris_cooling_1
      - type: conditional
        conditions:
          - entity: climate.2gig_technologies_ct101_thermostat_iris_heating_1
            state: "heat"
        card:
          type: custom:thermostat-card
          entity:  climate.2gig_technologies_ct101_thermostat_iris_heating_1

  - id: 1  # Automatically created id
    title: Lights
    cards:
      - id: 17b94b85afcb476b8d167ad93ee9a67c  # Automatically created id
        type: entities
        title: Living Room
        entities:
          - light.living_room_couch_1
          - light.living_room_couch_2
          - light.behind_tv_lamp
      - id: e386b3a5704c43faa3fc19bed4c07ca8  # Automatically created id
        type: entities
        title: Dining Room
        entities:
          - light.dining_room_lamp
          - light.6001948a98a2_1921680101
      - id: 4c7196226d3b48bfa63885669de0e55f  # Automatically created id
        type: entities
        title: Kitchen
        entities:
          - light.sink
          - light.oven
          - light.tuya_light_1
      - id: c4d371a5b82a413c96155e37b8c2cdba  # Automatically created id
        type: entities
        title: Bedroom Lights
        entities:
          - light.ge_12724_3way_dimmer_switch_level
          - light.flux_bedroom
      - id: e07642e0fbe34db09bf72ba4a16a60eb  # Automatically created id
        type: entities
        title: Sitting Room
        entities:
          - switch.tuya_switch_1
          - switch.sonoff_1
      - type: entities
        title: Extra
        entities:
          - switch.1712216593425625131334298f10a3cb
          - switch.1712213843127125131334298f10a49d

  - id: 2  # Automatically created id
    icon: mdi:television
    cards:
      - id: 2586d0867b184987994b40ec867cacf5  # Automatically created id
        type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: custom:button-card
                action: script
                icon: mdi:power
                entity: script.roku_button
                data: {button: power}
                color_off: var(--primary-color)
              - type: custom:button-card
                color_type: blank-card
              - type: custom:button-card
                action: service
                icon: mdi:volume-plus
                service:
                  domain: remote
                  action: send_command
                  data:
                    entity_id: remote.roku
                    command: volume_up
                color_off: var(--primary-color)
          - type: horizontal-stack
            cards:
              - type: custom:button-card
                action: service
                icon: mdi:backburger
                service:
                  domain: remote
                  action: send_command
                  data:
                    entity_id: remote.roku
                    command: back
                color_off: var(--primary-color)
              - type: custom:button-card
                action: service
                icon: mdi:home
                service:
                  domain: remote
                  action: send_command
                  data:
                    entity_id: remote.roku
                    command: home
                color_off: var(--primary-color)
              - type: custom:button-card
                action: service
                icon: mdi:volume-minus
                service:
                  domain: remote
                  action: send_command
                  data:
                    entity_id: remote.roku
                    command: volume_down
                color_off: var(--primary-color)
          - type: horizontal-stack
            cards:
              - type: custom:button-card
                color_type: blank-card
              - type: custom:button-card
                action: service
                icon: mdi:arrow-up-thick
                service:
                  domain: remote
                  action: send_command
                  data:
                    entity_id: remote.roku
                    command: up
                color_type: card
                color_off: var(--primary-color)
              - type: custom:button-card
                action: service
                icon: mdi:volume-mute
                service:
                  domain: remote
                  action: send_command
                  data:
                    entity_id: remote.roku
                    command: volume_mute
                color_off: var(--primary-color)
          - type: horizontal-stack
            cards:
              - type: custom:button-card
                action: service
                icon: mdi:arrow-left-thick
                service:
                  domain: remote
                  action: send_command
                  data:
                    entity_id: remote.roku
                    command: left
                color_type: card
                color_off: var(--primary-color)
              - type: custom:button-card
                action: service
                icon: mdi:check-outline
                service:
                  domain: remote
                  action: send_command
                  data:
                    entity_id: remote.roku
                    command: select
                color_type: card
                color_off: var(--primary-color)
              - type: custom:button-card
                action: service
                icon: mdi:arrow-right-thick
                service:
                  domain: remote
                  action: send_command
                  data:
                    entity_id: remote.roku
                    command: right
                color_type: card
                color_off: var(--primary-color)
          - type: horizontal-stack
            cards:
              - type: custom:button-card
                color_type: blank-card
              - type: custom:button-card
                action: service
                icon: mdi:arrow-down-thick
                service:
                  domain: remote
                  action: send_command
                  data:
                    entity_id: remote.roku
                    command: down
                color_type: card
                color_off: var(--primary-color)
              - type: custom:button-card
                color_type: blank-card
          - type: horizontal-stack
            cards:
              - type: custom:button-card
                action: service
                icon: mdi:replay
                service:
                  domain: remote
                  action: send_command
                  data:
                    entity_id: remote.roku
                    command: replay
                color_off: var(--primary-color)
              - type: custom:button-card
                color_type: blank-card
              - type: custom:button-card
                action: service
                icon: mdi:information-outline
                service:
                  domain: remote
                  action: send_command
                  data:
                    entity_id: remote.roku
                    command: info
                color_off: var(--primary-color)
          - type: horizontal-stack
            cards:
              - type: custom:button-card
                action: service
                icon: mdi:rewind
                service:
                  domain: remote
                  action: send_command
                  data:
                    entity_id: remote.roku
                    command: reverse
                color_off: var(--primary-color)
              - type: custom:button-card
                action: service
                icon: mdi:play-pause
                service:
                  domain: remote
                  action: send_command
                  data:
                    entity_id: remote.roku
                    command: play
                color_type: card
                color_off: var(--primary-color)
              - type: custom:button-card
                action: service
                icon: mdi:fast-forward
                service:
                  domain: remote
                  action: send_command
                  data:
                    entity_id: remote.roku
                    command: forward
                color_off: var(--primary-color)
      - id: aed7f2ab8a774007b883a0750900bfee  # Automatically created id
        type: entities
        title: Living Room
        show_header_toggle: false
        entities:
          - script.jeopardy
          - script.wii
      - id: 81949810d809465a823def5865d5e324  # Automatically created id
        type: media-control
        entity: media_player.roku
      - id: 5962e0f4870d45c69604c570a69d85e1  # Automatically created id
        type: media-control
        entity: media_player.living_room_tv
      - id: 2f7ccafbe8854226878bc4aa162d6514  # Automatically created id
        type: custom:mini-media-player
        entity: media_player.kitchen_speaker
        icon: mdi:cast
      - id: b136b74cb0554f9fa4f05825177dccf6  # Automatically created id
        type: custom:mini-media-player
        entity: media_player.bedroom_speaker
        icon: mdi:cast
      - id: 1438f0f086164423a7d92293f865cf05  # Automatically created id
        type: picture-entity
        image: https://images.pexels.com/photos/987586/pexels-photo-987586.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=240&w=495
        entity: script.roku_button
        name: Roku Remote

  - id: 3  # Automatically created id
    icon: mdi:settings
    cards:
      - type: conditional
        conditions:
          - entity: climate.2gig_technologies_ct101_thermostat_iris_cooling_1
            state_not: "heat"
        card:
          type: entities
          entities:
            - climate.2gig_technologies_ct101_thermostat_iris_cooling_1
      - type: conditional
        conditions:
          - entity: climate.2gig_technologies_ct101_thermostat_iris_heating_1
            state: "heat"
        card:
          type: entities
          entities:
            - climate.2gig_technologies_ct101_thermostat_iris_heating_1
      - id: a3f159521d614731ac7751320a17c25e  # Automatically created id
        type: entities
        title: More Details
        show_header_toggle: false
        entities:
          - sun.sun
          - sensor.dark_sky_summary
          - sensor.dark_sky_temperature
          - sensor.dark_sky_humidity
          - sensor.arrow_2_temperature
          - sensor.arrow_2_humidity
          - sensor.arrow_2_ldr
          - sensor.arrow_2_motion
      - id: 0dabe724acd54c8c8423bf5fbec61f15  # Automatically created id
        type: entities
        title: Speedtest
        show_header_toggle: false
        entities:
          - sensor.speedtest_download
          - sensor.speedtest_ping
      - id: af179a2d3d384240a91ac4f3be773c17  # Automatically created id
        type: entities
        title: Tracked Devices
        show_header_toggle: false
        entities:
          - device_tracker.spencer_phone
          - device_tracker.spencer_mac
          - device_tracker.lynsey_phone
          - device_tracker.lynsey_mac
          - device_tracker.kitchen_camera
      - id: 4376f466ef094499a10412772f03b3cf  # Automatically created id
        type: entities
        title: House Motion
        show_header_toggle: false
        entities:
          - binary_sensor.arrow_1_motion
          - binary_sensor.living_room_motion
      - id: 9b9f7042cd0c4171bb125d83875f2f3a  # Automatically created id
        type: entities
        title: Garage
        show_header_toggle: false
        entities:
          - sensor.garage_status
          - sensor.garage_distance
      - id: 97d8f655a09c430591e2ba1a0514d681  # Automatically created id
        type: vertical-stack
        cards:
          - type: history-graph
            title: Family Presence
            entities:
              - entity: input_select.family_status_dropdown
                name: Family
              - input_select.spencer_status_dropdown
              - input_select.lynsey_status_dropdown
          - type: entities
            show_header_toggle: false
            entities:
              - input_select.spencer_status_dropdown
              - input_select.lynsey_status_dropdown
              - input_select.family_status_dropdown
      - id: fe2749842ea94945b3747fd3f04dcf8f  # Automatically created id
        type: entities
        title: System
        show_header_toggle: false
        entities:
          - sensor.ha_uptime
          - input_select.hass_theme
          - group.all_automations
      - id: 6c98e6b747ff46c8bc1639f7af05f586  # Automatically created id
        type: entities
        title: SpaceX
        show_header_toggle: false
        entities:
          - sensor.spacex_next_mission_name
          - sensor.spacex_next_launch_date
          - sensor.spacex_next_launch_site
          - sensor.spacex_next_landing_type
          - sensor.spacex_next_rocket
