title: Oberstadt Home
resources:
  # local copy of card that I have edited
  - url: /local/roku-card.js?v=1
    type: module
  - url: /local/thermostat-card.js?v=1.1
    type: module
  # cards loaded via hacs
  - url: /community_plugin/compact-custom-header/compact-custom-header.js
    type: module
  - url: /community_plugin/mini-media-player/mini-media-player.js
    type: module
  - url: /community_plugin/lovelace-color-picker/color-picker.js
    type: js
  - url: /community_plugin/lovelace-card-tools/card-tools.js
    type: js
excluded_entities:
views:
  - title: Home
    icon: mdi:home
    background: var(--background-image)
    cards:
      - id: c9f11fedade648f5a56af91007986c32  # Automatically created id
        type: glance
        columns: 6
        entities:
          - entity: sensor.arrow_2_real_feel
            name: Inside
          - entity: sensor.dark_sky_apparent_temperature
            name: Outside
          - entity: group.house_motion
            icon: mdi:run-fast
            name: Motion
          - entity: input_select.spencer_status_dropdown
            icon: mdi:account
          - entity: input_select.lynsey_status_dropdown
            icon: mdi:account
          - entity: binary_sensor.garage_door
            name: Garage Door
      - id: b5080a0c1187408cae93b18ccc1223c9  # Automatically created id
        type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: entity-button
                entity: scene.evening
                icon: mdi:weather-sunset
                name: Evening
                tap_action:
                  action: call-service
                  service: scene.turn_on
                  service_data:
                    entity_id: scene.evening
              - type: entity-button
                entity: scene.bed_time
                icon: mdi:weather-night
                name: Bed Time
                tap_action:
                  action: call-service
                  service: scene.turn_on
                  service_data:
                    entity_id: scene.bed_time
              - type: entity-button
                entity: scene.good_night
                icon: mdi:sleep
                name: All Off
                tap_action:
                  action: call-service
                  service: scene.turn_on
                  service_data:
                    entity_id: scene.good_night
          - type: horizontal-stack
            cards:
              - type: entity-button
                entity: scene.romantic
                icon: mdi:heart
                name: Romantic
                tap_action:
                  action: call-service
                  service: scene.turn_on
                  service_data:
                    entity_id: scene.romantic
              - type: entity-button
                entity: script.wii
                icon: mdi:gamepad-variant
                name: Wii
                tap_action:
                  action: call-service
                  service: script.turn_on
                  service_data:
                    entity_id: script.wii
              - type: entity-button
                entity: scene.movie_playing
                icon: mdi:movie
                name: Movie
                tap_action:
                  action: call-service
                  service: scene.turn_on
                  service_data:
                    entity_id: scene.movie_playing
              - type: entity-button
                entity: scene.night_light
                icon: mdi:flashlight
                name: Night Light
                tap_action:
                  action: call-service
                  service: scene.turn_on
                  service_data:
                    entity_id: scene.night_light
              - type: entity-button
                entity: scene.night_light
                icon: mdi:baby-buggy
                name: Lily Bed Time
                tap_action:
                  action: call-service
                  service: scene.turn_on
                  service_data:
                    entity_id: scene.lily_bed_time
      - id: 148c092bb96847df98155f335be42be2  # Automatically created id
        type: entities
        title: Light Groups
        entities:
          - light.living_room_lights
          - light.kitchen_lights
          - light.bedroom_lights
          - light.sitting_room_lights
          - light.dining_room_lights
          - light.mood_lights
      - type: conditional
        conditions:
          - entity: climate.2gig_technologies_ct101_thermostat_iris_cooling_1
            state_not: "heat"
        card:
          type: custom:thermostat-card
          entity:  climate.2gig_technologies_ct101_thermostat_iris_cooling_1
      - type: conditional
        conditions:
          - entity: climate.2gig_technologies_ct101_thermostat_iris_heating_1
            state: "heat"
        card:
          type: custom:thermostat-card
          entity:  climate.2gig_technologies_ct101_thermostat_iris_heating_1

  - title: Lights
    background: var(--background-image)
    cards:
      - id: 17b94b85afcb476b8d167ad93ee9a67c  # Automatically created id
        type: entities
        title: Living Room
        entities:
          - light.living_room_couch_1
          - light.living_room_couch_2
          - light.behind_tv_lamp
      - id: e386b3a5704c43faa3fc19bed4c07ca8  # Automatically created id
        type: entities
        title: Dining Room
        entities:
          - light.dining_room_lamp
          - light.6001948a98a2_1921680101
      - id: 4c7196226d3b48bfa63885669de0e55f  # Automatically created id
        type: entities
        title: Kitchen
        entities:
          - light.sink
          - light.oven
          - light.tuya_light_1
      - id: c4d371a5b82a413c96155e37b8c2cdba  # Automatically created id
        type: entities
        title: Bedroom Lights
        entities:
          - light.ge_12724_3way_dimmer_switch_level
          - light.flux_bedroom
      - type: entities
        title: Lily Bedroom
        entities:
          - light.flux_lily_bedroom
      - id: e07642e0fbe34db09bf72ba4a16a60eb  # Automatically created id
        type: entities
        title: Sitting Room
        entities:
          - switch.tuya_switch_1
          - switch.sonoff_1
          - switch.meross_1
      - type: entities
        title: Extra
        entities:
          - switch.meross_2
      - type: custom:color-picker
        entity: light.mood_lights

  - title: Media
    icon: mdi:television
    background: var(--background-image)
    cards:
      - type: horizontal-stack
        cards:
          - type: entity-button
            entity: media_player.roku
            icon: mdi:netflix
            tap_action:
              action: call-service
              service: media_player.select_source
              service_data:
                entity_id: media_player.roku
                source: Netflix
          - type: entity-button
            entity: media_player.roku
            icon: mdi:amazon
            tap_action:
              action: call-service
              service: media_player.select_source
              service_data:
                entity_id: media_player.roku
                source: Prime Video
          - type: entity-button
            entity: media_player.roku
            icon: mdi:youtube
            tap_action:
              action: call-service
              service: media_player.select_source
              service_data:
                entity_id: media_player.roku
                source: YouTube
          - type: entity-button
            entity: media_player.roku
            icon: mdi:wii
            tap_action:
              action: call-service
              service: script.wii
          - type: entity-button
            entity: media_player.roku
            icon: alpha-j-circle
            tap_action:
              action: call-service
              service: script.jeopardy
      - type: custom:roku-card
        entity: media_player.roku
        tv: true
      - id: 81949810d809465a823def5865d5e324  # Automatically created id
        type: media-control
        entity: media_player.roku
      - id: 5962e0f4870d45c69604c570a69d85e1  # Automatically created id
        type: media-control
        entity: media_player.living_room_tv
      - type: vertical-stack
        cards:
          - type: custom:mini-media-player
            entity: media_player.kitchen_speaker
            icon: mdi:cast
          - type: custom:mini-media-player
            entity: media_player.bedroom_speaker
            icon: mdi:cast
          - type: custom:mini-media-player
            entity: media_player.googlehome9316
            icon: mdi:cast

  - title: Settings
    icon: mdi:settings
    background: var(--background-image)
    cards:
      - type: conditional
        conditions:
          - entity: climate.2gig_technologies_ct101_thermostat_iris_cooling_1
            state_not: "heat"
        card:
          type: entities
          entities:
            - climate.2gig_technologies_ct101_thermostat_iris_cooling_1
      - type: conditional
        conditions:
          - entity: climate.2gig_technologies_ct101_thermostat_iris_heating_1
            state: "heat"
        card:
          type: entities
          entities:
            - climate.2gig_technologies_ct101_thermostat_iris_heating_1
      - id: a3f159521d614731ac7751320a17c25e  # Automatically created id
        type: entities
        title: More Details
        show_header_toggle: false
        entities:
          - sun.sun
          - sensor.dark_sky_summary
          - sensor.dark_sky_temperature
          - sensor.dark_sky_humidity
          - sensor.arrow_2_temperature
          - sensor.arrow_2_humidity
      - id: 0dabe724acd54c8c8423bf5fbec61f15  # Automatically created id
        type: entities
        title: Speedtest
        show_header_toggle: false
        entities:
          - sensor.speedtest_download
          - sensor.speedtest_ping
      - id: af179a2d3d384240a91ac4f3be773c17  # Automatically created id
        type: entities
        title: Tracked Devices
        show_header_toggle: false
        entities:
          - device_tracker.spencer_phone
          - device_tracker.spencer_mac
          - device_tracker.lynsey_phone
          - device_tracker.lynsey_mac
          - device_tracker.kitchen_camera
      - id: 4376f466ef094499a10412772f03b3cf  # Automatically created id
        type: entities
        title: House Motion
        show_header_toggle: false
        entities:
          - binary_sensor.arrow_1_motion
          - binary_sensor.living_room_motion
      - id: 9b9f7042cd0c4171bb125d83875f2f3a  # Automatically created id
        type: entities
        title: Garage
        show_header_toggle: false
        entities:
          - sensor.garage_status
          - sensor.garage_distance
      - id: 97d8f655a09c430591e2ba1a0514d681  # Automatically created id
        type: vertical-stack
        cards:
          - type: history-graph
            title: Family Presence
            entities:
              - entity: input_select.family_status_dropdown
                name: Family
              - input_select.spencer_status_dropdown
              - input_select.lynsey_status_dropdown
          - type: entities
            show_header_toggle: false
            entities:
              - input_select.spencer_status_dropdown
              - input_select.lynsey_status_dropdown
              - input_select.family_status_dropdown
              - input_boolean.guest_mode
      - id: fe2749842ea94945b3747fd3f04dcf8f  # Automatically created id
        type: entities
        title: System
        show_header_toggle: false
        entities:
          - sensor.ha_uptime
          - input_select.hass_theme
      - id: 6c98e6b747ff46c8bc1639f7af05f586  # Automatically created id
        type: entities
        title: SpaceX
        show_header_toggle: false
        entities:
          - sensor.spacex_next_mission_name
          - sensor.spacex_next_launch_date
          - sensor.spacex_next_launch_site
          - sensor.spacex_next_landing_type
          - sensor.spacex_next_rocket
  - !include lovelace/automations_view.yaml
