title: Oberstadt Home
resources:
  - url: /local/button-card.js
    type: module
excluded_entities:
views:
  - icon: mdi:home
    cards:
      - type: glance
        entities:
          - entity: sensor.arrow_2_real_feel
            name: Inside
          - entity: sensor.dark_sky_apparent_temperature
            name: Outside
          - entity: group.house_motion
          - entity: input_select.spencer_status_dropdown
            icon: mdi:account
          - entity: input_select.lynsey_status_dropdown
            icon: mdi:account
          - entity: binary_sensor.garage_door
            name: Garage Door
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: custom:button-card
                entity: scene.evening
                icon: mdi:weather-sunset
                name: Evening
                action: turn_on
              - type: custom:button-card
                entity: scene.bed_time
                icon: mdi:weather-night
                name: Bed Time
                action: turn_on
              - type: custom:button-card
                entity: scene.good_night
                icon: mdi:sleep
                name: All Off
                action: turn_on
          - type: horizontal-stack
            cards:
              - type: custom:button-card
                entity: scene.romantic
                icon: mdi:heart
                name: Romantic
                action: turn_on
              - type: custom:button-card
                entity: script.wii
                icon: mdi:gamepad-variant
                name: Wii
                action: turn_on
              - type: custom:button-card
                entity: scene.movie_playing
                icon: mdi:movie
                name: Movie
                action: turn_on
      - type: entities
        title: Light Groups
        entities:
          - light.living_room_lights
          - light.kitchen_lights
          - light.bedroom_lights
          - group.sitting_room
          - light.mood_lights

  - title: Lights
    cards:
      - type: entities
        title: Living Room
        entities:
          - light.living_room_couch_1
          - light.living_room_couch_2
          - light.behind_tv_lamp
      - type: entities
        title: Dining Room
        entities:
          - light.dining_room_lamp
          - light.6001948a98a2_1921680101
      - type: entities
        title: Kitchen
        entities:
          - light.sink
          - light.oven
          - light.tuya_light_1
      - type: entities
        title: Bedroom Lights
        entities:
          - light.ge_12724_3way_dimmer_switch_level
          - light.flux_bedroom

  - icon: mdi:television
    cards:
      - type: picture-entity
        image: https://images.pexels.com/photos/987586/pexels-photo-987586.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=240&w=495
        entity: script.roku_button
        name: Roku Remote
      - type: entities
        title: Living Room
        show_header_toggle: false
        entities:
          - script.jeopardy
          - script.wii
      - type: media-control
        entity: media_player.roku
      - type: media-control
        entity: media_player.living_room_tv
      - type: media-control
        entity: media_player.kitchen_speaker
      - type: media-control
        entity: media_player.bedroom_speaker

  - icon: mdi:settings
    cards:
      - type: entities
        title: More Details
        show_header_toggle: false
        entities:
          - sun.sun
          - sensor.dark_sky_summary
          - sensor.dark_sky_temperature
          - sensor.dark_sky_humidity
          - sensor.arrow_2_temperature
          - sensor.arrow_2_humidity
          - sensor.arrow_2_ldr
          - sensor.arrow_2_motion
      - type: entities
        title: Speedtest
        show_header_toggle: false
        entities:
          - sensor.speedtest_download
          - sensor.speedtest_ping
      - type: entities
        title: Tracked Devices
        show_header_toggle: false
        entities:
          - device_tracker.spencer_phone
          - device_tracker.spencer_mac
          - device_tracker.lynsey_phone
          - device_tracker.lynsey_mac
          - device_tracker.kitchen_camera
      - type: entities
        title: House Motion
        show_header_toggle: false
        entities:
          - binary_sensor.arrow_1_motion
          - binary_sensor.living_room_motion
      - type: entities
        title: Garage
        show_header_toggle: false
        entities:
          - sensor.garage_status
          - sensor.garage_distance
      - type: entities
        title: Family Dropdowns
        show_header_toggle: false
        entities:
          - input_select.spencer_status_dropdown
          - input_select.lynsey_status_dropdown
      - type: entities
        title: System
        show_header_toggle: false
        entities:
          - sensor.ha_uptime
          - input_select.hass_theme
          - group.all_automations
