title: Oberstadt Home
resources:
  # local copy of card that I have edited
  - url: /local/thermostat-card.js?v=1.1
    type: module
  # cards loaded via hacs
  - url: /community_plugin/custom-header/custom-header.js
    type: module
  - url: /community_plugin/lovelace-card-tools/card-tools.js
    type: module
  - url: /community_plugin/mini-media-player/mini-media-player.js
    type: module
  - url: /community_plugin/roku-card/roku-card.js
    type: module
  - url: /community_plugin/lovelace-color-picker/color-picker.js
    type: js
excluded_entities:
custom_header:
  compact_mode: true
  hide_tabs:
    - 6
  hide_help: true
  hide_config: true
views:
  - title: Home
    icon: mdi:home
    background: var(--background-image)
    cards:
      - type: conditional
        conditions:
          - entity: cover.garage_door
            state: "open"
        card:
          type: entities
          show_header_toggle: false
          entities:
            - type: call-service
              icon: mdi:garage-open
              name: Garage Door
              action_name: Close
              service: cover.close_cover
              service_data:
                entity_id: cover.garage_door
      - type: glance
        columns: 6
        entities:
          - entity: sensor.avg_real_feel
            name: Inside
          - entity: sensor.dark_sky_apparent_temperature
            name: Outside
          - entity: group.house_motion
            icon: mdi:run-fast
            name: Motion
          - entity: input_select.spencer_status_dropdown
            icon: mdi:account
          - entity: input_select.lynsey_status_dropdown
            icon: mdi:account
          - entity: cover.garage_door
            name: Garage Door
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: entity-button
                entity: scene.evening
                icon: mdi:weather-sunset
                name: Evening
                tap_action:
                  action: call-service
                  service: scene.turn_on
                  service_data:
                    entity_id: scene.evening
              - type: entity-button
                entity: scene.good_night_lights
                icon: mdi:flashlight
                name: Night Light
                tap_action:
                  action: call-service
                  service: scene.turn_on
                  service_data:
                    entity_id: scene.good_night_lights
              - type: entity-button
                entity: script.good_night
                icon: mdi:sleep
                name: All Off
                tap_action:
                  action: call-service
                  service: script.good_night
          - type: horizontal-stack
            cards:
              - type: entity-button
                entity: scene.romantic
                icon: mdi:heart
                name: Romantic
                tap_action:
                  action: call-service
                  service: scene.turn_on
                  service_data:
                    entity_id: scene.romantic
              - type: entity-button
                entity: scene.movie_playing
                icon: mdi:movie
                name: Movie
                tap_action:
                  action: call-service
                  service: scene.turn_on
                  service_data:
                    entity_id: scene.movie_playing
              - type: entity-button
                entity: scene.lily_bed_time
                icon: mdi:baby-carriage
                name: Lily Bed Time
                tap_action:
                  action: call-service
                  service: scene.turn_on
                  service_data:
                    entity_id: scene.lily_bed_time
      - type: entities
        title: Light Groups
        entities:
          - light.living_room_lights
          - light.kitchen_lights
          - light.bedroom_lights
          - light.sitting_room_lights
          - light.dining_room_lights
          - light.mood_lights
      - type: vertical-stack
        cards:
          - type: custom:thermostat-card
            entity: climate.2gig_technologies_ct101_thermostat_iris_mode
          - type: conditional
            conditions:
              - entity: climate.2gig_technologies_ct101_thermostat_iris_mode
                state: "cool"
            card:
              type: entities
              show_header_toggle: false
              entities:
                - type: call-service
                  icon: mdi:radiator
                  name: Set thermostat to
                  action_name: Heat
                  service: climate.set_hvac_mode
                  service_data:
                    entity_id: climate.2gig_technologies_ct101_thermostat_iris_mode
                    hvac_mode: heat
          - type: conditional
            conditions:
              - entity: climate.2gig_technologies_ct101_thermostat_iris_mode
                state: "heat"
            card:
              type: entities
              show_header_toggle: false
              entities:
                - type: call-service
                  icon: mdi:air-conditioner
                  name: Set thermostat to
                  action_name: Cool
                  service: climate.set_hvac_mode
                  service_data:
                    entity_id: climate.2gig_technologies_ct101_thermostat_iris_mode
                    hvac_mode: cool
      - type: picture-glance
        title: Front Door
        camera_image: camera.front_door
        camera_view: live
        entities:
          - camera.front_door

  - title: Lights
    background: var(--background-image)
    icon: mdi:lightbulb-on-outline
    cards:
      - type: entities
        title: Living Room
        entities:
          - light.living_room_couch_1
          - light.living_room_couch_2
          - light.behind_tv_lamp
      - type: entities
        title: Dining Room
        entities:
          - light.dining_room_lamp
          - light.6001948a98a2_1921680101
      - type: entities
        title: Kitchen
        entities:
          - light.sink
          - light.oven
          - light.tuya_light_1
      - type: entities
        title: Bedroom Lights
        entities:
          - light.ge_12724_3way_dimmer_switch_level
          - light.flux_bedroom
      - type: entities
        title: Lily Bedroom
        entities:
          - light.flux_lily_bedroom
      - type: entities
        title: Sitting Room
        entities:
          - switch.tuya_switch_1
          - switch.sonoff_1
          - switch.meross_1
      - type: entities
        title: Extra
        entities:
          - switch.meross_2
          - switch.etekcity_1
          - switch.etekcity_2
      - type: custom:color-picker
        entity: light.mood_lights

  - title: Media
    icon: mdi:television
    background: var(--background-image)
    cards:
      - type: horizontal-stack
        cards:
          - type: entity-button
            entity: media_player.roku
            icon: mdi:netflix
            show_name: false
            tap_action:
              action: call-service
              service: media_player.select_source
              service_data:
                entity_id: media_player.roku
                source: Netflix
          - type: entity-button
            entity: media_player.roku
            icon: mdi:amazon
            show_name: false
            tap_action:
              action: call-service
              service: media_player.select_source
              service_data:
                entity_id: media_player.roku
                source: Prime Video
          - type: entity-button
            entity: media_player.roku
            icon: mdi:youtube
            show_name: false
            tap_action:
              action: call-service
              service: media_player.select_source
              service_data:
                entity_id: media_player.roku
                source: YouTube
          - type: entity-button
            entity: media_player.roku
            icon: mdi:wii
            show_name: false
            tap_action:
              action: call-service
              service: script.wii
          - type: entity-button
            entity: media_player.roku
            icon: mdi:alpha-j-circle
            show_name: false
            tap_action:
              action: call-service
              service: script.jeopardy
      - type: custom:roku-card
        entity: media_player.roku
        tv: true
      - type: media-control
        entity: media_player.roku
      - type: media-control
        entity: media_player.living_room_tv
      - type: vertical-stack
        cards:
          - type: custom:mini-media-player
            entity: media_player.kitchen_speaker
            icon: mdi:cast
          - type: custom:mini-media-player
            entity: media_player.bedroom_speaker
            icon: mdi:cast
          - type: custom:mini-media-player
            entity: media_player.googlehome9316
            icon: mdi:cast
      - type: horizontal-stack
        cards:
          - type: picture-entity
            entity: media_player.roku
            image: /local/nbc.png
            show_name: false
            show_state: false
            tap_action:
              action: call-service
              service: media_player.play_media
              service_data:
                entity_id: media_player.roku
                media_content_type: "TV"
                media_content_id: "2.1"
          - type: picture-entity
            entity: media_player.roku
            image: /local/cbs.png
            show_name: false
            show_state: false
            tap_action:
              action: call-service
              service: media_player.play_media
              service_data:
                entity_id: media_player.roku
                media_content_type: "TV"
                media_content_id: "6.1"
          - type: picture-entity
            entity: media_player.roku
            image: /local/abc.png
            show_name: false
            show_state: false
            tap_action:
              action: call-service
              service: media_player.play_media
              service_data:
                entity_id: media_player.roku
                media_content_type: "TV"
                media_content_id: "9.1"
          - type: picture-entity
            entity: media_player.roku
            image: /local/fox.png
            show_name: false
            show_state: false
            tap_action:
              action: call-service
              service: media_player.play_media
              service_data:
                entity_id: media_player.roku
                media_content_type: "TV"
                media_content_id: "35.1"

  - title: Settings
    icon: mdi:settings
    background: var(--background-image)
    path: settings
    cards:
      - type: entities
        entities:
          - climate.2gig_technologies_ct101_thermostat_iris_mode
      - type: entities
        title: More Details
        show_header_toggle: false
        entities:
          - sun.sun
          - sensor.dark_sky_summary
          - sensor.dark_sky_temperature
          - sensor.dark_sky_humidity
          - sensor.arrow_2_temperature
          - sensor.arrow_2_humidity
          - sensor.house_mean_temperature
          - sensor.house_mean_humidity
          - sensor.avg_real_feel
      - type: entities
        title: Speedtest
        show_header_toggle: false
        entities:
          - sensor.speedtest_download
          - sensor.speedtest_ping
      - type: entities
        title: Tracked Devices
        show_header_toggle: false
        entities:
          - device_tracker.spencer_phone
          - device_tracker.spencer_mac
          - device_tracker.lynsey_phone
          - device_tracker.lynsey_mac
          - device_tracker.kitchen_camera
      - type: entities
        title: House Motion
        show_header_toggle: false
        entities:
          - binary_sensor.arrow_1_motion
          - binary_sensor.living_room_motion
          - binary_sensor.arrow_9_motion
      - type: entities
        title: Garage
        show_header_toggle: false
        entities:
          - camera.camera_1
          - cover.garage_door
      - type: vertical-stack
        cards:
          - type: history-graph
            title: Family Presence
            entities:
              - entity: input_select.family_status_dropdown
                name: Family
              - input_select.spencer_status_dropdown
              - input_select.lynsey_status_dropdown
          - type: entities
            show_header_toggle: false
            entities:
              - input_select.spencer_status_dropdown
              - input_select.lynsey_status_dropdown
              - input_select.family_status_dropdown
              - input_boolean.guest_mode
      - type: entities
        title: System
        show_header_toggle: false
        entities:
          - sensor.ha_uptime
          - input_select.hass_theme
      - type: entities
        title: SpaceX
        show_header_toggle: false
        entities:
          - sensor.spacex_next_mission_name
          - sensor.spacex_next_launch_date
          - sensor.spacex_next_launch_site
          - sensor.spacex_next_landing_type
          - sensor.spacex_next_rocket
  - !include lovelace/arrows_view.yaml
  - !include lovelace/automations_view.yaml
  - title: wifi
    path: wifi
    cards:
      - type: markdown
        content: >
          ## Lovelace

          Starting with Home Assistant 0.72, we're experimenting with a new way of defining your interface. We're calling it the **Lovelace UI**.
