- alias: Camera Offline
  trigger:
    - platform: state
      entity_id: device_tracker.kitchen_camera
      to: 'not_home'
  action:
    - service: notify.notify
      data:
        message: 'Camera Offline'
        target:
          - !secret spencer_number