- alias: Camera Offline
  trigger:
    - platform: state
      entity_id: input_select.spencer_status_dropdown
      to: 'Away'
      for:
        minutes: 10
  condition:
    - condition: state
      entity_id: device_tracker.kitchen_camera
      state: 'not_home'
  action:
    - service: notify.pushbullet
      data:
        message: 'Camera Offline'
