- alias: Fam Away Door Open Alert
  trigger:
    - platform: state
      entity_id: binary_sensor.front_door
      to: "on"
    - platform: state
      entity_id: binary_sensor.garage_door
      to: "on"
  action:
    - condition: template
      value_template: "{{ states.input_select.family_status_dropdown.state in ['Away', 'Work', 'Extended Away'] }}"
    - condition: state
      entity_id: input_boolean.guest_mode
      state: "off"
    - service: notify.pushbullet
      data_template:
        message: "{{ trigger.to_state.attributes.friendly_name }} opened!"
