- alias: Garage Open While Away
  trigger:
    - platform: state
      entity_id: binary_sensor.garage_door
      to: "on"
  action:
    - delay:
        minutes: "1"
    - condition: state
      entity_id: group.friends_and_family
      state: "not_home"
    - service: notify.pushbullet
      data:
        message: "Garage Open"

- alias: Garage Open When Lynsey Comes Back
  trigger:
    - platform: state
      entity_id: binary_sensor.garage_door
      to: "on"
  action:
    - condition: state
      entity_id: input_select.lynsey_status_dropdown
      state: "Away"
    - condition: template
      value_template: "{{ states.input_select.spencer_status_dropdown.state in ['Home', 'Just Left'] }}"
    - condition: state
      entity_id: media_player.roku
      state: "playing"
    - service: light.turn_on
      data:
        entity_id: group.living_room_lights
        flash: short

- alias: Family Leave While Garage Open
  trigger:
    - platform: state
      entity_id: group.friends_and_family
      to: "not_home"
  condition:
    - condition: state
      entity_id: binary_sensor.garage_door
      state: "on"
  action:
    - service: notify.pushbullet
      data:
        message: "Garage Left Open"

- alias: Garage Open Too Long
  trigger:
    - platform: state
      entity_id: binary_sensor.garage_door
      to: "on"
      for:
        minutes: 60
  action:
    - service: notify.pushbullet
      data:
        message: "Garage Left Open"
