- alias: High Humidity
  trigger:
    - platform: numeric_state
      entity_id: sensor.arrow_2_humidity
      above: 50
  action:
    - service: notify.notify
      data:
        message: 'Home humidity above 50%!'
        target:
          - !secret spencer_number