- alias: Fam Away Motion Alert
  trigger:
    - platform: state
      entity_id: group.house_motion
      to: 'on'
  condition:
    - condition: state
      entity_id: group.family
      state: 'not_home'
  action:
    - service: notify.pushbullet
      data:
        message: 'Motion at home'
