- alias: Notify for new devices
  trigger:
    platform: event
    event_type: device_tracker_new_device
  action:
    - service: notify.pushbullet
      data_template:
        title: New device
        message: >
          {{trigger.event.data.host_name}}
          ({{trigger.event.data.entity_id}})
