- alias: SpaceX Launch Upcoming
  trigger:
    platform: numeric_state
    entity_id: sensor.spacex_hours_until
    below: 24
  action:
    service: persistent_notification.create
    data_template:
      title: SpaceX Launch Warning
      message: "Next launch in {{ states('sensor.spacex_hours_until') }} hours."
      notification_id: spacex_launch_info
