- alias: All Lights Button
  trigger:
    - platform: state
      entity_id: binary_sensor.arrow_5_button
      to: 'on'
  action:
    - service_template: >
        {% if is_state('group.all_lights.state', 'off') %}
          light.turn_on
        {% else %}
          light.turn_off
        {% endif %}
      entity_id: group.all_lights

- alias: RF Button 1 - Left Action
  trigger:
    - platform: state
      entity_id: binary_sensor.rf_button_one_left
      to: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.darkroom

- alias: RF Button 1 - Right Action
  trigger:
    - platform: state
      entity_id: binary_sensor.rf_button_one_right
      to: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.darkroom
