- alias: Nightstand Button
  trigger:
    - platform: state
      entity_id: binary_sensor.arrow_5_button
      to: 'on'
  action:
  - wait_for_trigger:
    - platform: state
      entity_id: binary_sensor.arrow_5_button
      to: 'off'
    continue_on_timeout: true
    timeout: 00:00:02
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ not wait.trigger }}'
      sequence:
      - service: script.good_night
    default:
    - service: scene.turn_on
      entity_id: scene.darkroom
  mode: single

- alias: RF Button 1 - Left Action
  trigger:
    - platform: state
      entity_id: binary_sensor.rf_button_one_left
      to: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.darkroom

- alias: RF Button 1 - Right Action
  trigger:
    - platform: state
      entity_id: binary_sensor.rf_button_one_right
      to: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.darkroom
