- alias: Nightstand Button - Short Press
  trigger:
    - platform: state
      entity_id: binary_sensor.arrow_5_button
      to: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.darkroom

- alias: Nightstand Button - Long Press
  trigger:
    - platform: state
      entity_id: binary_sensor.arrow_5_button
      to: 'on'
      for:
        seconds: 4
  action:
    service: scene.turn_on
    data_template:
      entity_id: >
        {% if states.input_boolean.guest_mode.state == 'on' %}
          scene.night_light
        {% else %}
          scene.good_night
        {% endif %}

- alias: RF Button 1 - Left Action
  trigger:
    - platform: state
      entity_id: binary_sensor.rf_button_one_left
      to: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.darkroom

- alias: RF Button 1 - Right Action
  trigger:
    - platform: state
      entity_id: binary_sensor.rf_button_one_right
      to: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.darkroom
