- alias: Night - Bedroom Mood Sleep Warning
  trigger:
    platform: time
    at: input_datetime.bedtime
  condition:
    - condition: state
      entity_id: light.ge_12724_3way_dimmer_switch_level
      state: "on"
  action:
    - service: script.warn_for_bed_time
    - delay:
        minutes: "5"
    - service: scene.turn_on
      entity_id: scene.darkroom

- alias: Night - Lily Night Light On
  trigger:
    platform: time
    at: "19:10:00"
  condition:
    - condition: template
      value_template: "{{ states.input_select.family_status_dropdown.state != 'Extended Away' }}"
  action:
    - service: light.turn_on
      entity_id: light.flux_lily_bedroom
      data:
        rgb_color: [255, 36, 0]
        brightness: 5
    - delay: 5
    - service: light.turn_on
      entity_id: light.flux_lily_bedroom
      data:
        rgb_color: [255, 36, 0]
        brightness: 5
