- alias: Night - Bedroom Mood Sleep Warning
  trigger:
    platform: time
    at: "23:25:00"
  condition:
    - condition: state
      entity_id: light.ge_12724_3way_dimmer_switch_level
      state: "on"
  action:
    - service: script.warn_for_bed_time

- alias: Night - Bedroom Sleep Time
  trigger:
    platform: time
    at: "23:30:00"
  condition:
    - condition: state
      entity_id: light.ge_12724_3way_dimmer_switch_level
      state: "on"
  action:
    - service: scene.turn_on
      entity_id: scene.darkroom
