- alias: Family Away
  trigger:
    - platform: state
      entity_id: input_select.family_status_dropdown
      to: "Away"
  action:
    - service: switch.turn_on
      entity_id: switch.meross_2
    - condition: state
      entity_id: input_boolean.guest_mode
      state: "off"
    - condition: state
      entity_id: climate.2gig_technologies_ct101_thermostat_iris_mode
      state: "cool"
    - service: climate.set_temperature
      data:
        entity_id: climate.2gig_technologies_ct101_thermostat_iris_mode
        temperature: 79
        hvac_mode: cool

- alias: Family Home
  trigger:
    - platform: state
      entity_id: input_select.family_status_dropdown
      to: "Just Arrived"
  action:
    - service: switch.turn_off
      entity_id: switch.meross_2
    - condition: state
      entity_id: climate.2gig_technologies_ct101_thermostat_iris_mode
      state: "cool"
    - service: climate.set_temperature
      data:
        entity_id: climate.2gig_technologies_ct101_thermostat_iris_mode
        temperature: 73
        hvac_mode: cool

- alias: Return to Neighborhood
  trigger:
    - platform: state
      entity_id: device_tracker.sm_g950u
      to: "Neighborhood"
    - platform: state
      entity_id: device_tracker.sm_g950u_2
      to: "Neighborhood"
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: "{{ states.input_select.family_status_dropdown.state in ['Away', 'Work', 'Extended Away'] }}"
      - condition: state
        entity_id: climate.2gig_technologies_ct101_thermostat_iris_mode
        state: "cool"
  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.2gig_technologies_ct101_thermostat_iris_mode
        temperature: 76
        hvac_mode: cool

- alias: Return from Walk
  trigger:
    - platform: state
      entity_id: binary_sensor.garage_door
      to: "on"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: light.flux_lily_bedroom
        state: "off"
      - condition: time
        after: "20:30:00"
        before: "23:30:00"
      - condition: state
        entity_id: climate.2gig_technologies_ct101_thermostat_iris_mode
        state: "cool"
  action:
    - service: scene.turn_on
      entity_id: scene.lily_bed_time
