- alias: IFTTT - Roku Channel
  trigger:
    platform: event
    event_type: ifttt_webhook_received
    event_data:
      action: call_roku_channel
  action:
    service: media_player.play_media
    data_template:
      entity_id: media_player.roku
      media_content_type: channel
      media_content_id: "{{ trigger.event.data.channel }}"

- alias: IFTTT - Roku Channel by Name
  trigger:
    platform: event
    event_type: ifttt_webhook_received
    event_data:
      action: call_roku_channel_by_name
  action:
    - service: system_log.write
      data_template:
        message: "{{ trigger.event.data.channel.upper() }}"
    - service: system_log.write
      data_template:
        message: >
          {% set channels = {
            'NBC':'2.1',
            'ABC':'9.1',
            'CBS':'6.1',
            'FOX':'35.1' } %}
          {{ channels[trigger.event.data.channel.upper()] }}
    - service: media_player.play_media
      data_template:
        entity_id: media_player.roku
        media_content_type: channel
        media_content_id: >
          {% set channels = {
            'NBC':'2.1',
            'ABC':'9.1',
            'CBS':'6.1',
            'FOX':'35.1' } %}
          {{ channels[trigger.event.data.channel.upper()] }}
