- alias: IFTTT - Scenes
  trigger:
    platform: event
    event_type: ifttt_webhook_received
    event_data:
      action: call_scene
  action:
    service: scene.turn_on
    data_template:
      entity_id: '{{ trigger.event.data.entity_id }}'

- alias: IFTTT - Roku
  trigger:
    platform: event
    event_type: ifttt_webhook_received
    event_data:
      action: call_roku
  action:
    service: roku_remote.press_button
    data_template:
      button: '{{ trigger.event.data.button }}'

- alias: IFTTT - Wii
  trigger:
    platform: event
    event_type: ifttt_webhook_received
    event_data:
      action: wii
  action:
    service: script.wii
