- alias: Mark Lily Door Open
  trigger:
    - platform: state
      entity_id: binary_sensor.arrow_10_door
      to: "on"
  action:
    - service: input_select.select_option
      data_template:
        entity_id: input_select.lily_door_status_dropdown
        option: Open

- alias: Mark Lily Door Closed
  trigger:
    - platform: state
      entity_id: binary_sensor.arrow_10_door
      to: "off"
  action:
    - service: input_select.select_option
      data_template:
        entity_id: input_select.lily_door_status_dropdown
        option: Closed

- alias: Mark Lily Door Unavailable
  trigger:
    - platform: state
      entity_id: binary_sensor.arrow_10_door
      to: "unavailable"
      for:
        minutes: 5
  action:
    - service: input_select.select_option
      data_template:
        entity_id: input_select.lily_door_status_dropdown
        option: Unavailable
