- alias: Jeopardy
  trigger:
    platform: time
    at: '18:59:00'
  condition:
    condition: time
    weekday:
      - mon
      - wed
      - thu
      - fri
  action:
    - service: script.jeopardy
