- alias: Autoplay Jeopardy
  trigger:
    platform: time
    at: '18:59:30'
  condition:
    condition: and
    conditions:
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
      - condition: template
        value_template: "{{ states.input_select.family_status_dropdown.state != 'Extended Away' }}"
  action:
    - service: script.jeopardy
