- alias: Mark person as just arrived
  mode: parallel
  trigger:
    - platform: state
      entity_id: device_tracker.spencer_phone
      from: "not_home"
      to: "home"
    - platform: state
      entity_id: device_tracker.lynsey_phone
      from: "not_home"
      to: "home"
  action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'device_tracker.spencer_phone' %}
            input_select.spencer_status_dropdown
          {% else %}
            input_select.lynsey_status_dropdown
          {% endif %}
        option: >
          {% if trigger.entity_id == 'device_tracker.spencer_phone' %}
            {% if states.input_select.spencer_status_dropdown.state == 'Just Left' %}
              Home
            {% else %}
              Just Arrived
            {% endif %}
          {% else %}
            {% if states.input_select.lynsey_status_dropdown.state == 'Just Left' %}
              Home
            {% else %}
              Just Arrived
            {% endif %}
          {% endif %}
    # if someone arives at home, change to just arrived unless previously home or just left then chagne to home
    - service: input_select.select_option
      data_template:
        entity_id: input_select.family_status_dropdown
        option: >
          {% if states.input_select.family_status_dropdown.state in ['Home', 'Just Left'] %}
            Home
          {% else %}
            Just Arrived
          {% endif %}

- alias: Mark person as home
  mode: parallel
  trigger:
    - platform: state
      entity_id: input_select.spencer_status_dropdown
      to: "Just Arrived"
      for:
        minutes: 10
    - platform: state
      entity_id: input_select.lynsey_status_dropdown
      to: "Just Arrived"
      for:
        minutes: 10
    - platform: state
      entity_id: input_select.spencer_status_dropdown
      from: "Just Left"
      to: "Just Arrived"
    - platform: state
      entity_id: input_select.lynsey_status_dropdown
      from: "Just Left"
      to: "Just Arrived"
  action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'input_select.spencer_status_dropdown' %}
            input_select.spencer_status_dropdown
          {% else %}
            input_select.lynsey_status_dropdown
          {% endif %}
        option: Home
    # if someone has been home for 10 minutes, the family is home
    - service: input_select.select_option
      data_template:
        entity_id: input_select.family_status_dropdown
        option: Home

- alias: Mark person as just left
  mode: parallel
  trigger:
    - platform: state
      entity_id: device_tracker.spencer_phone
      from: "home"
      to: "not_home"
    - platform: state
      entity_id: device_tracker.lynsey_phone
      from: "home"
      to: "not_home"
  action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'device_tracker.spencer_phone' %}
            input_select.spencer_status_dropdown
          {% else %}
            input_select.lynsey_status_dropdown
          {% endif %}
        option: Just Left
    # if someone leaves the network, only mark as just left if the other is not online
    - service: input_select.select_option
      data_template:
        entity_id: input_select.family_status_dropdown
        option: >
          {% if trigger.entity_id == 'device_tracker.spencer_phone' %}
            {% if states.device_tracker.lynsey_phone.state == 'home' %}
              {{ states.input_select.family_status_dropdown.state }}
            {% else %}
              Just Left
            {% endif %}
          {% else %}
            {% if states.device_tracker.spencer_phone.state == 'home' %}
              {{ states.input_select.family_status_dropdown.state }}
            {% else %}
              Just Left
            {% endif %}
          {% endif %}

- alias: Mark person as away
  mode: parallel
  trigger:
    - platform: state
      entity_id: input_select.spencer_status_dropdown
      to: "Just Left"
      for:
        minutes: 10
    - platform: state
      entity_id: input_select.lynsey_status_dropdown
      to: "Just Left"
      for:
        minutes: 10
  action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'input_select.spencer_status_dropdown' %}
            input_select.spencer_status_dropdown
          {% else %}
            input_select.lynsey_status_dropdown
          {% endif %}
        option: Away
    # if someone has been off the network for 10, only mark as away if other person is away
    - service: input_select.select_option
      data_template:
        entity_id: input_select.family_status_dropdown
        option: >
          {% if trigger.entity_id == 'input_select.spencer_status_dropdown' %}
            {% if states.input_select.lynsey_status_dropdown.state in ['Away', 'Work', 'Extended Away'] %}
              Away
            {% else %}
              {{ states.input_select.family_status_dropdown.state }}
            {% endif %}
          {% else %}
            {% if states.input_select.spencer_status_dropdown.state in ['Away', 'Work', 'Extended Away'] %}
              Away
            {% else %}
              {{ states.input_select.family_status_dropdown.state }}
            {% endif %}
          {% endif %}

- alias: Mark person as extended away
  mode: parallel
  trigger:
    - platform: state
      entity_id: input_select.spencer_status_dropdown
      to: "Away"
      for:
        hours: 24
    - platform: state
      entity_id: input_select.lynsey_status_dropdown
      to: "Away"
      for:
        hours: 24
  action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'input_select.spencer_status_dropdown' %}
            input_select.spencer_status_dropdown
          {% else %}
            input_select.lynsey_status_dropdown
          {% endif %}
        option: Extended Away
    # if someone is extended away, only mark as extended away if the other is extended away
    - condition: or
      conditions:
        - condition: and
          conditions:
            - condition: template
              value_template: "{{ trigger.entity_id == 'input_select.spencer_status_dropdown' }}"
            - condition: template
              value_template: "{{ states.input_select.lynsey_status_dropdown.state == 'Extended Away' }}"
        - condition: and
          conditions:
            - condition: template
              value_template: "{{ trigger.entity_id == 'input_select.lynsey_status_dropdown' }}"
            - condition: template
              value_template: "{{ states.input_select.spencer_status_dropdown.state == 'Extended Away' }}"
    - service: input_select.select_option
      data_template:
        entity_id: input_select.family_status_dropdown
        option: Extended Away

- alias: Mark person at work
  mode: parallel
  trigger:
    - platform: state
      entity_id: device_tracker.spencer_s_pixel_4
      to: "Work"
    - platform: state
      entity_id: device_tracker.pixel_4a
      to: "Work"
  action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'device_tracker.pixel_4a' %}
            input_select.lynsey_status_dropdown
          {% else %}
            input_select.spencer_status_dropdown
          {% endif %}
        option: Work
    # if someone gets marked as work, only mark as work if other person is work
    - service: input_select.select_option
      data_template:
        entity_id: input_select.family_status_dropdown
        option: >
          {% if trigger.entity_id == 'device_tracker.spencer_s_pixel_4' %}
            {% if states.input_select.lynsey_status_dropdown.state in ['Work', 'Extended Away'] %}
              Work
            {% else %}
              {{ states.input_select.family_status_dropdown.state }}
            {% endif %}
          {% else %}
            {% if states.input_select.spencer_status_dropdown.state in ['Work', 'Extended Away'] %}
              Work
            {% else %}
              {{ states.input_select.family_status_dropdown.state }}
            {% endif %}
          {% endif %}

- alias: Mark person leaving work
  mode: parallel
  trigger:
    - platform: state
      entity_id: device_tracker.spencer_s_pixel_4
      from: "work"
      to: "away"
    - platform: state
      entity_id: device_tracker.pixel_4a
      from: "work"
      to: "away"
  action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'device_tracker.pixel_4a' %}
            input_select.lynsey_status_dropdown
          {% else %}
            input_select.spencer_status_dropdown
          {% endif %}
        option: Away
    # if someone gets marked as leaving work, only mark as away if other person is not home
    - service: input_select.select_option
      data_template:
        entity_id: input_select.family_status_dropdown
        option: >
          {% if trigger.entity_id == 'device_tracker.spencer_s_pixel_4' %}
            {% if states.input_select.lynsey_status_dropdown.state in ['Away', 'Work', 'Extended Away'] %}
              Away
            {% else %}
              {{ states.input_select.family_status_dropdown.state }}
            {% endif %}
          {% else %}
            {% if states.input_select.spencer_status_dropdown.state in ['Away', 'Work', 'Extended Away'] %}
              Away
            {% else %}
              {{ states.input_select.family_status_dropdown.state }}
            {% endif %}
          {% endif %}
