- alias: Stop Working
  id: 7cf6716d-d428-4bc5-875d-07df003954ad
  trigger:
    platform: time
    at: "17:30:00"
  condition:
    condition: state
    entity_id: binary_sensor.workday_sensor
    state: "on"
  action:
    - service: media_player.play_media
      target:
        entity_id: media_player.spotify_spencer_t_oberstadt
      data:
        media_content_id: https://open.spotify.com/track/1A5V1sxyCLpKJezp75tUXn?si=6e853fd210324b0a
        media_content_type: music
