- alias: Sunset
  trigger:
    platform: state
    entity_id: binary_sensor.sun_down
    to: 'on'
  action:
    - service: scene.turn_on
      data_template:
        entity_id: >
          {% if states.input_select.family_status_dropdown.state == 'Extended Away' %}
            scene.away_evening
          {% else %}
            scene.evening
          {% endif %}

- alias: Sunrise
  trigger:
    platform: state
    entity_id: binary_sensor.sun_down
    to: 'off'
  action:
    - service: light.turn_on
      entity_id: light.flux_lily_bedroom
      data:
        rgb_color: [255, 36, 0]
        brightness: 5
    - service: light.turn_off
      entity_id: light.flux_lily_bedroom
