- alias: Sunset
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 8
  condition:
    - condition: time
      after: '10:00:00'
      before: '02:00:00'
  action:
    - service: scene.turn_on
      entity_id: scene.evening
