- alias: Morning - Bedroom White-noise Stop
  trigger:
    platform: time_pattern
    minutes: "/1"
  condition:
    condition: and
    conditions:
      - condition: time
        after: '04:00:00'
        before: '12:00:00'
      - condition: template
        value_template: >
          {% if (state_attr('input_datetime.special_wakeup', 'timestamp') | int) != 0 %}
            {{ states('sensor.time') == (state_attr('input_datetime.special_wakeup', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}
          {% elif states('binary_sensor.workday_sensor') == 'on' %}
            {{ states('sensor.time') == (state_attr('input_datetime.weekday_wakeup', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}
          {% else %}
            {{ states('sensor.time') == (state_attr('input_datetime.weekend_wakeup', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}
          {% endif %}
  action:
    - service: media_player.turn_off
      entity_id: media_player.bedroom_speaker
    - service: input_datetime.set_datetime
      entity_id: input_datetime.special_wakeup
      data:
        time: '00:00:00'
