- platform: rpi_gpio
  ports:
    17: PIR Living Room
- platform: trend
  sensors:
    ac_running:
      entity_id: sensor.arrow_2_real_feel
      sample_duration: 600
      min_gradient: -.00033
      max_samples: 6
      device_class: cold

- platform: template
  sensors:
    garage_door:
      friendly_name: "Garage Open"
      device_class: garage_door
      value_template: >-
        {{ states.sensor.garage_status.state == 'open' }}
    living_room_motion:
      friendly_name: "Living Room Motion"
      device_class: motion
      value_template: "{{ states('binary_sensor.pir_living_room') }}"

- platform: mqtt
  state_topic: "/devices/mqtt_arrow_1/events"
  name: "Arrow 1 Motion"
  device_class: motion
  value_template: '{{ value_json.motion }}'
