- platform: workday
  country: USA
  province: FL

- platform: template
  sensors:
    sun_down:
      value_template: >-
        {{ state_attr('sun.sun', 'elevation') < 8 }}

- platform: template
  sensors:
    spencer_charging:
      value_template: >-
        {{ states.sensor.sm_g950u_battery_level_2.attributes.is_charging }}

# button 1 Left: 9864A1
# button 1 Right: 9864A2
- platform: mqtt
  name: RF Button One - Left
  payload_on: "9864A1"
  state_topic: "tele/sonoff_rf/RESULT"
  value_template: "{{ value_json.RfReceived.Data }}"
  off_delay: 3
  availability_topic: "tele/sonoff_rf/LWT"
  payload_available: Online
  payload_not_available: Offline

- platform: mqtt
  name: RF Button One - Right
  payload_on: "9864A2"
  state_topic: "tele/sonoff_rf/RESULT"
  value_template: "{{ value_json.RfReceived.Data }}"
  off_delay: 3
  availability_topic: "tele/sonoff_rf/LWT"
  payload_available: Online
  payload_not_available: Offline

- platform: mqtt
  name: Front Door
  payload_on: "236136"
  state_topic: "tele/sonoff_rf/RESULT"
  value_template: "{{ value_json.RfReceived.Data }}"
  off_delay: 10
  device_class: door
  availability_topic: "tele/sonoff_rf/LWT"
  payload_available: Online
  payload_not_available: Offline

- platform: mqtt
  name: Garage Entry
  payload_on: "21CE46"
  state_topic: "tele/sonoff_rf/RESULT"
  value_template: "{{ value_json.RfReceived.Data }}"
  off_delay: 10
  device_class: door
  availability_topic: "tele/sonoff_rf/LWT"
  payload_available: Online
  payload_not_available: Offline

- platform: mqtt
  name: Bedroom Door
  payload_on: "A7790A"
  payload_off: "A7790E"
  state_topic: "tele/sonoff_rf/RESULT"
  value_template: "{{ value_json.RfReceived.Data }}"
  device_class: door
  availability_topic: "tele/sonoff_rf/LWT"
  payload_available: Online
  payload_not_available: Offline

- platform: mqtt
  name: RF Bridge Available
  payload_on: Online
  payload_off: Offline
  state_topic: "tele/sonoff_rf/LWT"
  device_class: connectivity
