- platform: template
  sensors:
    garage_door:
      friendly_name: "Garage Open"
      device_class: garage_door
      value_template: >-
        {{ states.sensor.garage_status.state == 'open' }}
    arrow_1_motion:
      friendly_name: "Arrow 1 Motion"
      device_class: motion
      value_template: "{{ states('sensor.arrow_1_motion') == 'on' }}"
    spencer_charging:
      value_template: >-
        {{ states.device_tracker.google_maps_114754196444501299267.attributes.battery_charging }}

- platform: mqtt
  name: Living Room Motion
  state_topic: "/devices/mqtt_arrow_4/binary_sensor/bs1/state"
  device_class: motion
  availability_topic: "/devices/mqtt_arrow_4/status"

- platform: mqtt
  name: Arrow 5 Button
  state_topic: "/devices/mqtt_arrow_5/binary_sensor/bs1/state"
  availability_topic: "/devices/mqtt_arrow_5/status"

# button 1 Left: 9864A1
# button 1 Right: 9864A2
- platform: mqtt
  name: RF Button One - Left
  payload_on: "9864A1"
  state_topic: "tele/sonoff_rf/RESULT"
  value_template: '{{ value_json.RfReceived.RfKey }}'
  off_delay: 3

- platform: mqtt
  name: RF Button One - Right
  payload_on: "9864A2"
  state_topic: "tele/sonoff_rf/RESULT"
  value_template: '{{ value_json.RfReceived.RfKey }}'
  off_delay: 3
