- platform: rpi_gpio
  ports:
    17: PIR Living Room

- platform: template
  sensors:
    garage_door:
      friendly_name: "Garage Open"
      device_class: garage_door
      value_template: >-
        {{ states.sensor.garage_status.state == 'open' }}
    living_room_motion:
      friendly_name: "Living Room Motion"
      device_class: motion
      value_template: "{{ states('binary_sensor.pir_living_room') == 'on' }}"
    arrow_1_motion:
      friendly_name: "Arrow 1 Motion"
      device_class: motion
      value_template: "{{ states('sensor.arrow_1_motion') == 'on' }}"
    spencer_charging:
      value_template: >-
        {{ states.device_tracker.google_maps_114754196444501299267.attributes.battery_charging }}
