- platform: rpi_gpio
  ports:
    17: PIR Living Room
- platform: trend
  sensors:
    ac_running:
      entity_id: sensor.arrow_2_real_feel
      sample_duration: 600
      min_gradient: -.00033
      max_samples: 6
      device_class: cold
