- platform: template
  covers:
    garage_door:
      friendly_name: "Garage Door"
      device_class: garage
      value_template: "{{ states.binary_sensor.garage_door.state == 'on' }}"
      open_cover:
        service: switch.turn_on
        data:
          entity_id: switch.garage_remote
      close_cover:
        service: switch.turn_on
        data:
          entity_id: switch.garage_remote
      availability_template: "{{ states.switch.garage_remote.state != 'unavailable' }}"
      icon_template: >-
        {% if states.binary_sensor.garage_door.state == 'on' %}
          mdi:garage-open
        {% else %}
          mdi:garage
        {% endif %}
