- platform: flux_led
  automatic_add: True
  devices:
    192.168.0.112:
      name: flux_bedroom
    192.168.0.101:
      name: 6001948a98a2_1921680101
    192.168.0.122:
      name: flux_lily_bedroom
    192.168.0.195:
      name: kitchen_cabinet

- platform: mqtt
  name: Bulb 4578
  state_topic: "stat/tasmota-4578/POWER"
  command_topic: "cmnd/tasmota-4578/POWER"
  availability_topic: "tele/tasmota-4578/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  brightness_state_topic: "stat/tasmota-4578/RESULT"
  brightness_value_template: "{{ value_json.Dimmer }}"
  brightness_command_topic: "cmnd/tasmota-4578/DIMMER"
  brightness_scale: 100
  color_temp_state_topic: "stat/tasmota-4578/RESULT"
  color_temp_value_template: "{{ value_json.Color }}"
  color_temp_command_topic: "cmnd/tasmota-4578/CT"

- platform: group
  name: Living Room Lights
  entities:
    - light.living_room_couch_1
    - light.living_room_couch_2
    - light.behind_tv_lamp
- platform: group
  name: Kitchen Lights
  entities:
    - light.sink
    - light.oven
    - light.bulb_4578
    - light.kitchen_cabinet
- platform: group
  name: Bedroom Lights
  entities:
    - light.ge_12724_3way_dimmer_switch_level
    - light.flux_bedroom
- platform: group
  name: Mood Lights
  entities:
    - light.6001948a98a2_1921680101
    - light.flux_bedroom
- platform: group
  name: Sitting Room Lights
  entities:
    - light.paper_lamp
    - light.buffet_lamp
    - light.sitting_room_couch
- platform: group
  name: Dining Room Lights
  entities:
    - light.dining_room_lamp

- platform: switch
  name: Buffet Lamp
  entity_id: switch.sonoff_1
- platform: switch
  name: Sitting Room Couch
  entity_id: switch.teckin_6634
- platform: switch
  name: Paper Lamp
  entity_id: switch.meross_1
