- platform: flux_led
  automatic_add: True
  devices:
    192.168.0.112:
      name: flux_bedroom
    192.168.0.101:
      name: 6001948a98a2_1921680101
- platform: group
  name: Living Room Lights
  entities:
    - light.living_room_couch_1
    - light.living_room_couch_2
    - light.behind_tv_lamp
- platform: group
  name: Kitchen Lights
  entities:
    - light.sink
    - light.oven
    - light.tuya_light_1
- platform: group
  name: Bedroom Lights
  entities:
    - light.ge_12724_3way_dimmer_switch_level
    - light.flux_bedroom
- platform: group
  name: Mood Lights
  entities:
    - light.6001948a98a2_1921680101
    - light.flux_bedroom
- platform: group
  name: Sitting Room Lights
  entities:
    - light.buffet_lamp
    - light.sitting_room_couch

- platform: switch
  name: Buffet Lamp
  entity_id: switch.sonoff_1
- platform: switch
  name: Sitting Room Couch
  entity_id: switch.tuya_switch_1
