- platform: group
  name: Living Room Lights
  entities:
    - light.living_room_couch_1
    - light.living_room_couch_2
    - light.behind_tv_lamp
- platform: group
  name: Kitchen Lights
  entities:
    - light.sink
    - light.oven
    - light.bulb_4578
    - light.kitchen_cabinet
- platform: group
  name: Bedroom Lights
  entities:
    - light.ge_12724_3way_dimmer_switch_level
    - light.flux_bedroom
- platform: group
  name: Mood Lights
  entities:
    - light.6001948a98a2_1921680101
    - light.flux_bedroom
- platform: group
  name: Sitting Room Lights
  entities:
    - light.paper_lamp
    - light.buffet_lamp
    - light.sitting_room_couch
    - light.wled_1
- platform: group
  name: Dining Room Lights
  entities:
    - light.dining_room_lamp

- platform: switch
  name: Buffet Lamp
  entity_id: switch.sonoff_1
- platform: switch
  name: Sitting Room Couch
  entity_id: switch.teckin_6634
- platform: switch
  name: Paper Lamp
  entity_id: switch.meross_1
- platform: switch
  name: Front Door Light
  entity_id: switch.gosund_sw1
- platform: switch
  name: Kitchen Overhead Lights
  entity_id: switch.gosund_sw2
