- platform: flux_led
  automatic_add: True
  devices:
    192.168.0.112:
      name: flux_bedroom
- platform: group
  name: Living Room Lights
  entities:
    - light.living_room_couch_1
    - light.living_room_couch_2
    - light.behind_tv_lamp
- platform: group
  name: Kitchen Lights
  entities:
    - light.sink
    - light.oven
    - light.tuya_light_1
- platform: group
  name: Bedroom Lights
  entities:
    - light.ge_12724_3way_dimmer_switch_level
    - light.flux_bedroom
- platform: group
  name: Mood Lights
  entities:
    - light.6001948a98a2_1921680101
    - light.flux_bedroom
- platform: mqtt
  name: Sonoff 1
  state_topic: "stat/sonoff1/POWER"
  command_topic: "cmnd/sonoff1/POWER"
  availability_topic: "tele/sonoff1/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
