- platform: darksky
  api_key: !secret darksky
  monitored_conditions:
    - summary
    - icon
  update_inverval:
    minutes: 30

- platform: speedtest
  monitored_conditions:
    - ping
    - download

- platform: mqtt
  state_topic: "/devices/mqtt_arrow_2/events"
  name: "Arrow 1 Humidity"
  unit_of_measurement: "%"
  value_template: '{{ value_json.humidity | round(1) }}'

- platform: mqtt
  state_topic: "/devices/mqtt_arrow_2/events"
  name: "Arrow 1 Temperature"
  unit_of_measurement: "°C"
  value_template: '{{ value_json.temperature | round(1) }}'

- platform: mqtt
  state_topic: "/devices/mqtt_arrow_2/events"
  name: "Arrow 1 Real Feel"
  unit_of_measurement: "°F"
  value_template: '{{ value_json.heat_index | round(1) }}'
