- platform: darksky
  api_key: !secret darksky
  monitored_conditions:
    - summary
    - apparent_temperature
    - temperature
    - humidity
    - weather
  scan_interval:
    minutes: 30

- platform: mqtt
  state_topic: "/devices/mqtt_arrow_2/events"
  name: "Arrow 2 Humidity"
  unit_of_measurement: "%"
  value_template: '{{ value_json.humidity | round(1) }}'

- platform: mqtt
  state_topic: "/devices/mqtt_arrow_2/events"
  name: "Arrow 2 Temperature"
  unit_of_measurement: "°C"
  value_template: '{{ value_json.temperature | round(1) }}'

- platform: mqtt
  state_topic: "/devices/mqtt_arrow_2/events"
  name: "Arrow 2 Real Feel"
  unit_of_measurement: "°F"
  value_template: '{{ value_json.heat_index | round(1) }}'

- platform: mqtt
  state_topic: "/devices/mqtt_arrow_2/events"
  name: "Arrow 2 LDR"
  unit_of_measurement: "LUX"
  value_template: '{{ value_json.lux }}'

- platform: mqtt
  state_topic: "/devices/mqtt_arrow_2/motion"
  name: "Arrow 2 Motion"
  value_template: '{{ value_json.motion }}'

- platform: mqtt
  state_topic: "/devices/mqtt_arrow_1/events"
  name: "Arrow 1 Motion"
  value_template: '{{ value_json.motion }}'

- platform: mqtt
  state_topic: "/devices/mqtt_arrow_3/state"
  name: "Garage Distance"
  unit_of_measurement: "cm"
  value_template: '{{ value_json.distance }}'

- platform: mqtt
  state_topic: "/devices/mqtt_arrow_3/state"
  name: "Garage Status"
  value_template: '{{ value_json.state }}'

- platform: uptime
  name: HA Uptime
  unit_of_measurement: hours

- platform: rest
  name: SpaceX
  json_attributes:
    - mission_name
    - launch_site
    - rocket
  value_template: '{{ value_json["launch_date_unix"] }}'
  resource: 'https://api.spacexdata.com/v2/launches/next'

- platform: template
  sensors:
    spacex_next_launch_date:
      friendly_name: 'Next Launch Date'
      value_template: '{{ states.sensor.spacex.state | int | timestamp_custom("%m/%d/%Y %H:%M")}}'
    spacex_next_rocket:
      friendly_name: 'Rocket'
      value_template: '{{ states.sensor.spacex.attributes["rocket"]["rocket_name"] }}'
    spacex_next_landing_type:
      friendly_name: 'Landing Type'
      value_template: '{{ states.sensor.spacex.attributes["rocket"]["first_stage"]["cores"][0]["landing_type"] }}'
    spacex_next_launch_site:
      friendly_name: 'Launch Site'
      value_template: '{{ states.sensor.spacex.attributes["launch_site"]["site_name"] }}'
    spacex_next_mission_name:
      friendly_name: 'Mission Name'
      value_template: '{{ states.sensor.spacex.attributes["mission_name"] }}'

    spencers_battery:
      unit_of_measurement: '%'
      value_template: '{{ states.device_tracker.google_maps_114754196444501299267.attributes.battery_level | round(0) }}'

    roku_source:
      value_template: '{{ states.media_player.roku.attributes.source }}'
