- platform: darksky
  api_key: 972d05aa595120020dde2b33a3808a45
  monitored_conditions:
    - summary
    - icon
  update_inverval:
    minutes: 30

- platform: speedtest
  monitored_conditions:
    - ping
    - download
    - upload
