- platform: darksky
  api_key: !secret darksky
  monitored_conditions:
    - summary
    - icon
  update_inverval:
    minutes: 30

- platform: speedtest
  monitored_conditions:
    - ping
    - download
    - upload
