- platform: mqtt
  name: Sonoff 1
  state_topic: "stat/sonoff1/POWER"
  command_topic: "cmnd/sonoff1/POWER"
  availability_topic: "tele/sonoff1/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
# - platform: rpi_rf
#   gpio: 18
#   switches:
#     aux1:
#       pulselength: 190
#       code_on: 349955
#       code_off: 349964
#     aux2:
#       pulselength: 190
#       code_on: 349635
#       code_off: 349644
