esphome:
  name: arrow_8
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret mqtt_wifi_ssid
  password: !secret mqtt_wifi_password
  fast_connect: on

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: !secret mqtt_password

# Enable Web server.
# web_server:
#   port: 80

binary_sensor:
  - platform: gpio
    pin:
      number: D3
    name: Arrow 8 Flash Button
    on_press:
      - switch.turn_on: relay
    on_release:
      - switch.turn_off: relay

switch:
  - platform: template
    name: "Garage Remote"
    icon: "mdi:garage"
    id: relay_wrapper
    turn_on_action:
    - switch.turn_on: relay
    - delay: 500ms
    - switch.turn_off: relay

  - platform: gpio
    name: Arrow 8 Relay
    pin:
      number: D5
      inverted: yes
    id: relay
    restore_mode: ALWAYS_OFF

  # Switch to restart the device.
  - platform: restart
    name: Arrow 8 Restart


# Sensors with general information.
sensor:
  # Uptime sensor.
  - platform: uptime
    name: Arrow 8 Uptime

  # WiFi Signal sensor.
  - platform: wifi_signal
    name: Arrow 8 WiFi Signal
    update_interval: 60s
