esphome:
  name: arrow_8
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret mqtt_wifi_ssid
  password: !secret mqtt_wifi_password
  fast_connect: on

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: !secret mqtt_password

# Enable Web server.
# web_server:
#   port: 80

binary_sensor:
  - platform: gpio
    pin:
      number: D3
    name: Arrow 8 Flash Button

switch:
  # Switch to restart the device.
  - platform: restart
    name: Arrow 8 Restart

# Sensors with general information.
sensor:
  # Uptime sensor.
  - platform: uptime
    name: Arrow 8 Uptime

  # WiFi Signal sensor.
  - platform: wifi_signal
    name: Arrow 8 WiFi Signal
    update_interval: 60s
