esphome:
  name: mqtt_arrow_4
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret mqtt_wifi_ssid
  password: !secret mqtt_wifi_password

# Enable logging
logger:

api:

ota:
  password: !secret mqtt_password

binary_sensor:
  - platform: gpio
    pin: D5
    name: Living Room Motion
    device_class: motion

switch:
  - platform: restart
    name: Arrow 4 Restart
