esphome:
  name: mqtt_arrow_4
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret mqtt_wifi_ssid
  password: !secret mqtt_wifi_password

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_user
  password: !secret mqtt_password
  topic_prefix: '/devices/mqtt_arrow_4'

# Enable logging
logger:

# Enable Home Assistant API
# api:

ota:
  password: !secret mqtt_password

binary_sensor:
  - platform: gpio
    pin: D5
    name: bs1
    device_class: motion

switch:
  - platform: restart
    name: Arrow 4 Restart
