esphome:
  name: mqtt_arrow_2
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret mqtt_wifi_ssid
  password: !secret mqtt_wifi_password

logger:

api:

ota:
  password: !secret mqtt_password

sensor:
  - platform: dht
    pin: D7
    model: DHT22
    temperature:
      name: "Arrow 2 Temperature"
    humidity:
      name: "Arrow 2 Humidity"
    update_interval: 120s
