esphome:
  name: mqtt_arrow_6
  platform: ESP32
  board: esp32dev

wifi:
  ssid: !secret mqtt_wifi_ssid
  password: !secret mqtt_wifi_password

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: !secret mqtt_password

esp32_camera:
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  reset_pin: GPIO15
  # Image settings
  name: Camera 1
  resolution: 800x600
  max_framerate: 5 fps

