esphome:
  name: nfc-reader-1

esp8266:
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Nfc-Reader-1 Fallback Hotspot"
    password: "8uxbAa114mG1"

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "XiGg7ua9EMiPuJOwq/MYQdqThFZcxDzYm3PXO8jX8cg="

captive_portal:

ota:
  password: !secret mqtt_password

# Enable Web server.
web_server:
  port: 80

spi:
  clk_pin: D5
  mosi_pin: D7
  miso_pin: D6

switch:
  - platform: restart
    name: NFC Scanner 1 Restart

pn532_spi:
  cs_pin: D0
  update_interval: 1s
  on_tag:
    then:
      # https://esphome.io/components/binary_sensor/pn532.html#ndef-reading
      - homeassistant.tag_scanned: !lambda |
          if (!tag.has_ndef_message()) {
            return x;
          }
          auto message = tag.get_ndef_message();
          auto records = message->get_records();
          for (auto &record : records) {
            std::string payload = record->get_payload();
            size_t pos = payload.find("https://www.home-assistant.io/tag/");
            if (pos != std::string::npos) {
              return payload.substr(pos + 34);
            }
          }
          return x;
